#ifndef _ROGUEBAN_H
#define _ROGUEBAN_H

#define TILESET "./Zilk_16x16.png"
#define SCREEN_WIDTH 640
#define SCREEN_HEIGHT 480
#define FONT_SIZE 16
#define ZOOM 1
#define NUM_ROWS SCREEN_HEIGHT / FONT_SIZE
#define NUM_COLS SCREEN_WIDTH / FONT_SIZE
#define FPS 60
#define MAX_GAME_OBJECTS_SIZE 1024



#endif // _ROGUEBAN_H
